# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=7)),
                ('pagado', models.BooleanField(default=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Paciente')),
            ],
        ),
        migrations.RenameField(
            model_name='adjunto',
            old_name='consulta',
            new_name='ficha',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sesiones',
            field=models.TextField(max_length=1024),
        ),
    ]
