# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_auto_20160628_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='ficha',
            new_name='paciente',
        ),
    ]
