# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20160628_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
